ifneq (,$(wildcard .env))
    include .env
    export
endif

help:  ## Show help
	@grep -hE '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

# --------- setup --------- #

install:  ## Install dependencies with uv
	uv sync --all-extras

# --------- code quality --------- #

format:  ## Run pre-commit hooks
	pre-commit run -a

lint:  ## Run ruff linter
	uv run ruff check src/ tests/

# --------- testing --------- #

test:  ## Run not slow tests
	uv run pytest -k "not slow"

test-full:  ## Run all tests
	uv run pytest

# --------- training --------- #

train:  ## Train the model
	uv run python src/train.py

eval:  ## Evaluate the model
	uv run python src/eval.py

# --------- dvc --------- #

dvc-pull:  ## Pull data from DVC remote
	dvc pull

dvc-push:  ## Push data to DVC remote
	dvc push

dvc-status:  ## Show DVC status
	dvc status

dvc-repro:  ## Reproduce DVC pipeline
	dvc repro

# --------- mlflow --------- #

mlflow:  ## Start MLflow UI session
	uv run mlflow ui --backend-store-uri sqlite:///logs/mlflow/mlruns.db

# --------- commitizen --------- #

commit:  ## Create a conventional commit
	uv run cz commit

bump:  ## Bump project version
	uv run cz bump

changelog:  ## Generate CHANGELOG.md
	uv run cz changelog

# --------- cleanup --------- #

clean:  ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs:  ## Clean logs
	rm -rf logs/**
