_target_: src.models.audio_classification_module.AudioClassificationModule

num_classes: 10
target_name: class_id
compile: false
monitor_metric: val/acc
warmup_type: null
warmup_rate: null

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 50
  eta_min: 1e-6

net:
  _target_: src.models.components.base.Model

  input_block:
    _target_: src.models.components.input_blocks.passthrough.SequentialNumericalPassthrough

  hidden_blocks:
    - _target_: src.models.components.hidden_blocks.sequential_pooling.Pooling
      emb_dim: ${data.mel_spectrogram_cfg.obj.n_mels}

  output_block:
    _target_: src.models.components.output_blocks.classifiers.flat_linear.FlatLinearClassifier
    # MaxMinMeanPooling (default) triples the emb_dim
    emb_dim: ${eval:${data.mel_spectrogram_cfg.obj.n_mels} * 3}
    n_layers: 2
    dropout: 0.1
    activation: gelu
    num_classes: ${model.num_classes}
