_target_: src.models.audio_classification_module.AudioClassificationModule

num_classes: ${data.schema.fields.class_id.value.cardinality}
target_field: ${data.schema.fields.class_id.name}
input_adapter:
  _target_: src.models.components.batch_adapter.BatchToModelInputAdapter
  numerical_field: ${data.schema.fields.mel_spectrogram.name}
  padding_mask_field: ${data.schema.fields.mel_spectrogram.name}
compile: false
monitor_metric: val/acc
warmup_type: null
warmup_rate: null

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-4
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 40
  eta_min: 1e-6

net:
  _target_: src.models.components.base.BlockModel

  input_block:
    _target_: src.models.components.input_blocks.spectrogram_cnn.SpectrogramCNNEncoder
    channels: [32, 64, 128]
    embedding_dim: 256
    kernel_size: 3
    dropout: 0.15
    activation: gelu
    use_batch_norm: true
    global_pool: avgmax

  hidden_blocks: []

  output_block:
    _target_: src.models.components.output_blocks.classifiers.flat_linear.FlatLinearClassifier
    emb_dim: ${model.net.input_block.embedding_dim}
    n_layers: 2
    dropout: 0.2
    activation: gelu
    num_classes: ${model.num_classes}
